In [2]:
import torch
import pandas as pd

In [6]:
l1 = [1, 2, 3]
l2 = l1[:]

In [7]:
l1[0] = 5
del l1[2]

In [8]:
l1

[5, 2]

In [9]:
l2

[1, 2, 3]

In [12]:
l1 = [1, 2, 3, 4, 5, 6, 7]
l1[:5] = [2]

In [13]:
l1

[2, 6, 7]

In [14]:
list(zip([1, 2, 3], [2, 3]))

[(1, 2), (2, 3)]

In [10]:
embeddings = torch.randn((100, 100))
embeddings.shape

torch.Size([100, 100])

In [12]:
embeddings_params = torch.nn.Parameter(embeddings)

In [9]:
torch.empty((5, 5))

tensor([[-5.1400e-27,  4.5738e-41,  1.6154e-34,  0.0000e+00,  1.4013e-45],
        [ 0.0000e+00,  1.6031e-34,  0.0000e+00,  1.2293e-34,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.7897e-34,  0.0000e+00,  1.1459e-35],
        [ 0.0000e+00,  6.6327e+24,  4.5737e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [17]:
embed_to_hidden_weight = torch.nn.Parameter(torch.empty((100, 200)))
torch.nn.init.xavier_uniform_(embed_to_hidden_weight, gain=1.0)

Parameter containing:
tensor([[-0.1144,  0.0119,  0.0488,  ...,  0.0749,  0.0378,  0.0296],
        [ 0.0312,  0.0569,  0.0853,  ..., -0.0993, -0.0161,  0.0862],
        [-0.0973, -0.0420, -0.1115,  ...,  0.0697,  0.0761,  0.1316],
        ...,
        [-0.0796,  0.0365,  0.0720,  ...,  0.0469,  0.1018,  0.0383],
        [ 0.0339, -0.0075,  0.1350,  ...,  0.0816, -0.1005, -0.0349],
        [-0.1330, -0.0272,  0.0619,  ..., -0.0679,  0.0772,  0.0644]],
       requires_grad=True)

In [29]:
torch.Tensor([[1, 2, 3], [2, 4, 4]]).view(1, -1)

tensor([[1., 2., 3., 2., 4., 4.]])

In [45]:
embeddings[[torch.tensor([[3, 5], [3, 5]])]].flatten().shape

torch.Size([400])